### ISSUE TITLE
why my cam fps is 0?

### ISSUE THREAD

**Issue by lee05311** [sho-87/webcam-eye-tracker#1]
My web cam fps is 0.
why?
How can make faster?
![스크린샷 2023-09-14 120901](https://github.com/sho-87/webcam-eye-tracker/assets/38288887/9dfb5e1d-5ead-4594-b490-0d362fe7c2c4)

**Comment by thesimonho** [comment]
Most likely because of not running on a dedicated GPU, or running on a device like a laptop that doesnt have enough CPU performance. the video capture can be quite heavy

**Comment by lee05311** [comment]
![스크린샷 2023-09-14 145410](https://github.com/sho-87/webcam-eye-tracker/assets/38288887/e960f187-3ebb-4d83-88e7-6bc17f68e1ad)
Is have another way to check run on gpu?

**Comment by thesimonho** [comment]
I think thats the primary way. 

Im not sure whats happening - I havent looked at this code in quite a few years

Does opencv webcam capture work OK by itself in its own separate script?

**Comment by Terkiss** [comment]
When I run the cam in example_face_Detection.ipynb, it is smooth.
However, the cam executed in collect_data is frame 0.
Now cv2 also uses CUDA, but it is still the same.

**Comment by lee05311** [comment]
When I run the cam in example_face_Detection.ipynb, it is smooth.
However, the cam executed in collect_data is frame 0.
Now cv2 also uses CUDA, but it is still the same.

**Comment by thesimonho** [comment]
maybe it is a gpu selection problem

in the collect_data.py file, try passing in `gpu=0` into both the detector and predictor here: https://github.com/sho-87/webcam-eye-tracker/blob/master/1_collect_data.py#L67-L72

**Comment by lee05311** [comment]
Now that I think about it, I think the file went wrong when I did git clone. It seems that the file was not downloaded properly because it was a large file or it was overdue.

**Comment by thesimonho** [comment]
yes thats possible. I use Git LFS but I only have limited bandwidth/space each month
